# Generated by Django 2.2.7 on 2019-11-24 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.TextField(default='haIPnRjdUdxsjBsEZuFyeBhxIleiixR7', max_length=32)),
                ('api_key', models.TextField(max_length=32)),
                ('log_message', models.TextField(max_length=2048)),
                ('log_properties', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('optional_args_key', models.TextField(default=None, max_length=2048)),
                ('optional_args_value', models.TextField(default=None, max_length=2048)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recorded_on', models.DateTimeField(auto_now_add=True, verbose_name='date_recorded')),
            ],
            options={
                'verbose_name': 'table to save logs with optional properties',
                'db_table': 'logs',
            },
        ),
    ]
