# Generated by Django 2.2.7 on 2019-11-24 18:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecordLog', '0002_auto_20191124_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_id',
            field=models.TextField(default='TU9eeokZ7Or9IFLBIevaChua2Vk3Bp4M', max_length=32),
        ),
        migrations.AlterField(
            model_name='logs',
            name='log_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
