# Generated by Django 2.2.7 on 2019-11-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecordLog', '0003_auto_20191124_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_id',
            field=models.TextField(default='tyvW3kOZ1wVH0bsOENrgriV6hkmRbBDm', max_length=32),
        ),
        migrations.AlterField(
            model_name='logs',
            name='optional_args_key',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='logs',
            name='optional_args_value',
            field=models.TextField(default='', max_length=2048),
        ),
    ]
