# Generated by Django 2.2.7 on 2019-11-26 17:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecordLog', '0004_auto_20191124_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(default='p2qmORVaOpGur5yLMbLMkdIKFyxZMiIg', max_length=32)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'table to save api keys',
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='LogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.TextField(default='LEBmmiBuQgZQxjAgqjmIvIVAM7PJclYs', max_length=32)),
                ('api_key', models.TextField(max_length=32)),
                ('log_message', models.TextField(max_length=2048)),
                ('log_properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('optional_args_key', models.TextField(default='', max_length=2048)),
                ('optional_args_value', models.TextField(default='', max_length=2048)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recorded_on', models.DateTimeField(auto_now_add=True, verbose_name='date_recorded')),
            ],
            options={
                'verbose_name': 'table to save logs with optional properties',
                'db_table': 'logs',
            },
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
