# Generated by Django 2.2.7 on 2019-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecordLog', '0005_auto_20191126_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeymodel',
            name='api_key',
            field=models.TextField(default='2ci0MC5ESUbPsOjkW5t37Wf2fpcceY8k', max_length=32),
        ),
        migrations.AlterField(
            model_name='logsmodel',
            name='log_id',
            field=models.TextField(default='B6pc9lGmlTY9Kveqp4MOkFqqG4P7DzSB', max_length=32),
        ),
    ]
