# Generated by Django 2.2.7 on 2019-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecordLog', '0006_auto_20191126_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeymodel',
            name='api_key',
            field=models.TextField(default='k0B3FKuLAz8XV6VH3zTX9VEUxDbBLdoz', max_length=32),
        ),
        migrations.AlterField(
            model_name='logsmodel',
            name='log_id',
            field=models.TextField(default='LqDQDG3OtObq79odeZpmyko9eHwj14VD', max_length=32),
        ),
    ]
