# Generated by Django 2.2.7 on 2019-11-26 18:25

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('RecordLog', '0007_auto_20191126_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeymodel',
            name='api_key',
            field=models.TextField(default=utils.helpers.generate_random_string, max_length=32),
        ),
        migrations.AlterField(
            model_name='apikeymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logsmodel',
            name='log_id',
            field=models.TextField(default=utils.helpers.generate_random_string, max_length=32),
        ),
    ]
