# Generated by Django 2.2.7 on 2019-11-27 18:36

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(default=utils.helpers.generate_random_string, max_length=32)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'table to save api keys',
                'db_table': 'api_key',
            },
        ),
    ]
